---@class hover_translate.Provider
---@field build_request fun(text: string, config: hover_translate.TranslatorInternalConfig): string, string, table Build request URL and payload for translation provider.
---@field parse_response fun(result: table): string Parse response from translation provider.
